name: health_care
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  liquid_progress_indicator: ^0.4.0
  getwidget: 2.0.5
  firebase_core: 1.17.1
  cloud_firestore: 3.1.17
  shared_preferences: 2.0.15
  firebase_auth: 3.3.19
  timezone: 0.8.0
  flutter_local_notifications: ^9.5.3+1
  workmanager: ^0.4.1
  flutter_native_timezone: 2.0.0
  flutter_launcher_icons: ^0.9.2
  rxdart: 0.27.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter_icons: 
  android: launcher_icon
  image_path: assets/images/playstore.png
  ios: true

flutter: 
  assets: 
    - assets/images/
    - assets/images/icon/bmi/
  uses-material-design: true

